#!/bin/bash

rm ./tmp/*.png

#1 
#povray desk.pov +Q11 +A +HR +RVP +WT64 Initial_Frame=1 Final_Frame=450 Initial_Clock=0 Final_Clock=15 Output_File_Name=./tmp/

#2
povray ani_fan.pov +Q11 +A +HR +RVP +WT64 Initial_Frame=1 Final_Frame=450 Initial_Clock=0 Final_Clock=15 Output_File_Name=./tmp/

rm ./tmp/ani_fan.mp4
ffmpeg -framerate 30 -i ./tmp/ani_fan%03d.png ./tmp/ani_fan.mp4
#rm ./tmp/*.png

